# Generated by Django 2.2.18 on 2021-03-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='123abc', max_length=64),
        ),
    ]
