# Generated by Django 2.2.18 on 2021-03-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0002_player_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='home_place',
        ),
        migrations.AddField(
            model_name='player',
            name='Country',
            field=models.CharField(default='USA', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='dateob',
            field=models.DateField(help_text='MM/DD/YYYY'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
