# Generated by Django 2.2.18 on 2021-03-15 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportiasts', '0003_auto_20210315_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='events',
            name='player',
        ),
        migrations.AddField(
            model_name='events',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
