# Generated by Django 2.2.18 on 2021-03-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0005_auto_20210315_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventt',
            field=models.CharField(default='Sportiasts Event', max_length=500),
        ),
    ]
