# Generated by Django 2.2.18 on 2021-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0006_events_eventt'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(default='sportiasts-event', unique=True),
            preserve_default=False,
        ),
    ]
