# Generated by Django 3.2 on 2021-04-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0008_alter_events_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='discord_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
    ]
