# Generated by Django 3.2 on 2021-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0009_auto_20210420_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='maps_url',
            field=models.URLField(null=True),
        ),
    ]
