# Generated by Django 3.2 on 2021-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0010_events_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='maps_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
