# Generated by Django 3.2 on 2021-04-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0011_alter_events_maps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
    ]
