# Generated by Django 3.2 on 2021-04-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0012_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='EventType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportiasts.eventtype'),
        ),
    ]
