# Generated by Django 3.2 on 2021-04-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportiasts', '0013_events_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='EventType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventType', to='sportiasts.eventtype'),
        ),
    ]
